spring.datasource:
  url: jdbc:h2:./camunda-db;DB_CLOSE_DELAY=-1;MVCC=TRUE;DB_CLOSE_ON_EXIT=FALSE
  username: sa
  password: sa
spring.h2.console.enabled: true
camunda.bpm.admin-user:
    id: demo
    password: demo
    firstName: Demo
server.port: 8080
