version: "2"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.6.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
      - elasticsearch-logs:/usr/share/elasticsearch/logs
    restart: always
    mem_limit: 2g

  optimize:
    image: registry.camunda.cloud/optimize:3.0.0-alpha2
    environment:
      - OPTIMIZE_CAMUNDABPM_REST_URL=http://camunda:8080/engine-rest
      - OPTIMIZE_ELASTICSEARCH_HOST=elasticsearch
      - OPTIMIZE_EVENT_BASED_PROCESSES_ENABLED=true
      - OPTIMIZE_EVENT_BASED_PROCESSES_USER_IDS=['demo']
      - OPTIMIZE_EVENT_INGESTION_ACCESS_TOKEN=mytoken
    volumes:
      - ./licenses/OptimizeLicense.txt:/optimize/environment/OptimizeLicense.txt
    container_name: optimize
    ports:
      - 8090:8090
    depends_on:
      - camunda
      - elasticsearch
    restart: always
    mem_limit: 2g

  camunda:
    image: registry.camunda.cloud/cambpm-ee/camunda-bpm-platform-ee:7.12.3
    container_name: camunda
    ports:
      - 8080:8080
    restart: always
    mem_limit: 1g

volumes:
  elasticsearch-data:
  elasticsearch-logs:
